apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etax-was-hpa
  namespace: etax-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etax-was
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etax-app-hpa
  namespace: etax-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etax-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etax-edms-hpa
  namespace: etax-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etax-edms
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etax-sms-hpa
  namespace: etax-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etax-sms
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etax-report-hpa
  namespace: etax-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etax-report
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etax-web-hpa
  namespace: etax-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etax-web
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
