apiVersion: v1
kind: Secret
metadata:
  name: etax-was-webhook-secret
  namespace: etax-app
type: Opaque
stringData:
  WebHookSecretKey: etax-was-secret-2026
---
apiVersion: v1
kind: Secret
metadata:
  name: etax-app-webhook-secret
  namespace: etax-app
type: Opaque
stringData:
  WebHookSecretKey: etax-app-secret-2026
---
apiVersion: v1
kind: Secret
metadata:
  name: etax-edms-webhook-secret
  namespace: etax-app
type: Opaque
stringData:
  WebHookSecretKey: etax-edms-secret-2026
---
apiVersion: v1
kind: Secret
metadata:
  name: etax-sms-webhook-secret
  namespace: etax-app
type: Opaque
stringData:
  WebHookSecretKey: etax-sms-secret-2026
---
apiVersion: v1
kind: Secret
metadata:
  name: etax-report-webhook-secret
  namespace: etax-app
type: Opaque
stringData:
  WebHookSecretKey: etax-report-secret-2026
